language: node_js
node_js:
    - "10"
script:
    - npm run all-no-doc
after_script: 
    - "cd typescript-plugin-proactive-code-fixes && npm run test-coverage && cd .. && cat ./typescript-plugin-proactive-code-fixes/coverage/lcov.info | ./typescript-plugin-proactive-code-fixes/node_modules/coveralls/bin/coveralls.js"