language: node_js
node_js:
    - "10"
script:
    - npm run all-no-doc && cd typescript-plugin-proactive-code-fixes && npm run test-coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js